### ISSUE TITLE
[1.16] Severe lag after letting the coker run for a while

### ISSUE THREAD

**Issue by MuteTiefling** [TwistedGate/ImmersivePetroleum#30] opened 2021-05-31 12:58 UTC
### Description of the issue
Noticed some new multiblocks in IP recently and set them up to give them a try. As it was a test world, I set up some creative bins to feed bitumen into the Coker and had the output collected by IE belts and sent to a black hole unit/tank. After leaving it running overnight I came back to see my game had largely become unresponsive. No crash, just severe TPS lag. 

### Versions and Modlist
ImmersiveEngineering-1.16.5-5.0.0-135
ImmersivePetroleum-1.16.5-3.3.0-4
Forge 36.1.16
Possibly unrelated Crash log for the rest: 
[crash-2021-03-31_23.03.54-server.txt](https://github.com/TwistedGate/ImmersivePetroleum/files/6570344/crash-2021-03-31_23.03.54-server.txt)
This was generated when I force quit the game due to it being unresponsive.

### Crash Log
Not a crash log, since it didn't actually crash directly. But I was able to profile it with VisualVM. Saved a snapshot and am including it here. 
[snapshot-1622465184292.zip](https://github.com/TwistedGate/ImmersivePetroleum/files/6570347/snapshot-1622465184292.zip)

**Comment by TwistedGate** [comment] 2021-07-10 16:05
I cant for the live of me reproduce this, while also having VisualVM running in the background

**Comment by MuteTiefling** [comment] 2021-07-11 00:40
I have a suspicion it was right on the edge of loaded chunks. If I recall correctly, however, when I went over to clean it up there were just piles of output items sitting on the belts, not moving

**Comment by TwistedGate** [comment] 2021-07-11 01:21
hm, could've perhaps been the items then~

**Comment by MuteTiefling** [comment] 2021-07-11 01:35
most likely, just seemed odd for them to accumulate like that

**Comment by TwistedGate** [comment] 2022-01-16 09:19
Closing due to not being reproducable in any way

**Closed as completed by TwistedGate** 2022-01-16 09:19 UTC
Labels: Bug :lady_beetle:, MC-1.16.5
