### ISSUE TITLE
projector not working with rubidium

### ISSUE THREAD

**Issue by KristoferDanger** [TwistedGate/ImmersivePetroleum#150] opened 2023-04-30 17:47 UTC
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### Immersive Petroleum Version

4.1.0-19

### Current Behaviour

Projector not working with rubidium, is there any way to fix this without uninstalling rubidium?

### Expected Behaviour

.

### Reproduction Steps

.

### Debug Crash Log

.

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment] 2023-05-03 14:22
Duplicate of #147

**Closed as completed** 2023-05-03 14:22 UTC
Labels: Bug :lady_beetle:, Duplicate
