### ISSUE TITLE
Missing oil

### ISSUE THREAD

**Issue by RudyDinis** [TwistedGate/ImmersivePetroleum#151] opened 2023-05-06 02:40 UTC
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### Immersive Petroleum Version

4.10-19

### Current Behaviour

Hi, i have 
I put the immersive petroleum mod in a modded server but no crude oil lake is present, then I tried in a single player world but still none, finally I tried using the command /ip reservoir locate but i have this (see attachment)
![image](https://user-images.githubusercontent.com/60667200/236594200-df517907-f4c3-4b51-89c7-f6974b4c6a54.png)

### Expected Behaviour

Without oil in the world the mod is therefore unusable

### Reproduction Steps

1. download the mod
2. start a world
3. view no oil

### Debug Crash Log

https://pastebin.com/7aQUZ1rd

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by MrMorgan0** [comment] 2023-05-06 06:23
Hi there, oil reservoir doesn't exist even you generating new world? 
Anyway, make sure about mod Data Pack available or not, when you generating new world. 
Also try run IE and IP without any mod, if it works without any issue, you should find another mods which causing that issue. Something like Biomes o plenty or another mods that changing world generation.

**Comment by RudyDinis** [comment] 2023-05-06 14:18
> Hi there, oil reservoir doesn't exist even you generating new world? Anyway, make sure about mod Data Pack available or not, when you generating new world. Also try run IE and IP without any mod, if it works without any issue, you should find another mods which causing that issue. Something like Biomes o plenty or another mods that changing world generation.

Yeah even if I create a new world there is none and I have no mods other than IE and IP

**Comment by TwistedGate** [comment] 2023-05-06 17:49
Duplicate of #144

**Comment by RudyDinis** [comment] 2023-05-06 21:04
> Duplicate of #144

it's a little different, he has oil in some places while me nowhere, even in the minecraft:overworld there is none unlike him

**Comment by TwistedGate** [comment] 2023-05-11 22:25
it'd suggest trying [1.18.2-4.1.0-21](https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum/files/4526462) if you havent already

**Comment by redbike02** [comment] 2023-05-27 20:56
i am running 1.18.2-4.1.0-21 and have the same problem

**Comment by TwistedGate** [comment] 2023-05-28 13:07
Unable to reproduce. Found oil everywhere i looked on a fresh world

**Closed as completed** 2023-08-13 05:41 UTC
Labels: Bug :lady_beetle:, Duplicate
