### ISSUE TITLE
Crash with chained oil tanks in loading chunks

### ISSUE THREAD

**Issue by SgerbwdGwyn** [TwistedGate/ImmersivePetroleum#185] opened 2024-05-08 12:19 UTC
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.4-170

### Immersive Petroleum Version

4.2.0-28

### How did it happen?

This crash has happened twice so far on my server, and seems to only happen when I fly quickly from a particular direction toward my chunks that have oil tanks.

I've only got about 6 or so end-to-end, so I imagine it's just the tanks trying to read each other's data while the others haven't loaded in yet.
I don't think it's actually related to the other mods I'm using, since it's only when travelling long distances quickly in an aircraft from another mod.

I've been unable to fix it myself, but if another player logs in and I teleport them directly on top of the tankers it seems to fix it (until the next time)

### Crash Log

https://gist.github.com/MynachMelyn/3c84f0893ec9c350b7bb2076e47324bd

**Comment by TwistedGate** [comment] 2024-05-09 02:14
Duplicate of #179 (Though *this one* is much more readable than the other =P)

**Closed as not planned by TwistedGate** 2024-05-09 02:14 UTC
Labels: Duplicate, Crash :boom:
