### ISSUE TITLE
[1.16.5-3.2.0-3] ImmersivePetroleum Error loading mods

### ISSUE THREAD

**Issue by YOUNG-WLI** [TwistedGate/ImmersivePetroleum#25] opened 2021-05-27 07:38 UTC
forge-36.1.23
ImmersiveEngineering-1.16.5-5.0.0-135
ImmersivePetroleum-1.16.5-3.2.0-3
![image](https://user-images.githubusercontent.com/41699862/119785019-c5dae500-bf09-11eb-9ca4-f5f33af696c6.png)

Crash report is also attached.
[crash-2021-05-27_16.28.52-fml.txt](https://github.com/TwistedGate/ImmersivePetroleum/files/6552000/crash-2021-05-27_16.28.52-fml.txt)

**Comment by TwistedGate** [comment] 2021-05-27 07:57
Did not read the changelog did ya

also Duplicate of #24

**Closed as completed by TwistedGate** 2021-05-27 07:57 UTC

**Comment by YOUNG-WLI** [comment] 2021-05-27 08:06
I missed it. Sorry for my carelessness. thank you for the reply.
